name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Retreive cached dependecies
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: make test
